# Play a sound when player joins.
playerJoinSound: true

# Send a global chat message when player joins
playerJoinMsg: false

# If playerJoinMsg is enabled, this enables/disables a special message for admins that joins
adminJoinMsg: true

# Play sound when someone sends a message
chatSound: true