# Play a sound when player joins.
# 1 = true, 0 = false
playerJoinSound: 1

# Send a global chat message when player joins
# 1 = true, 0 = false
playerJoinMsg: 0

# If playerJoinMsg is enabled, this enables/disables a special message for admins that joins
# 1 = true, 0 = false
adminJoinMsg: 1

# Play sound when someone sends a message
chatSound: 1